INSERT INTO USER(USER_NAME, PASSWORD) VALUES ('admin', '$2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6');
-- username: admin, password: password
INSERT INTO ITEM(ITEM_NAME, PRICE) VALUES('Chicken MOMO', '150');
INSERT INTO ITEM(ITEM_NAME, PRICE) VALUES('Buff MOMO', '130');
INSERT INTO ITEM(ITEM_NAME, PRICE) VALUES('Chowmein', '150');
INSERT INTO ITEM(ITEM_NAME, PRICE) VALUES('Thupka', '170');
INSERT INTO ITEM(ITEM_NAME, PRICE) VALUES('Coke', '50');
INSERT INTO ITEM(ITEM_NAME, PRICE) VALUES('Mineral water', '30');



